import { POST_STATUSES } from "./constants";

export const demoContentPosts = [
  {
    id: "demo-1",
    platform: "Instagram",
    contentType: "Caption Post",
    pillar: "Mindset Shifts",
    goal: "Engagement",
    tone: "Grounded, hopeful, direct",
    topic: "Reset after a hard week",
    context: "Encourage honest reflection and small action.",
    status: POST_STATUSES[0],
    hook: "You do not need a new life overnight. You need one honest step today.",
    body:
      "Growth is rarely loud. Sometimes it looks like a hard conversation, a boundary kept, or a quiet decision to stop betraying yourself.",
    cta: "Save this for the day you need a reset.",
    hashtags: ["#Change180", "#MindsetShift", "#PersonalGrowth"],
    visualDirection: "Soft cream quote graphic with teal heading.",
    createdAt: "2026-03-10T15:00:00.000Z",
    scheduledFor: "",
  },
  {
    id: "demo-2",
    platform: "LinkedIn",
    contentType: "Carousel",
    pillar: "Practical Action",
    goal: "Education",
    tone: "Reflective and clarifying",
    topic: "Five signs you need clarity",
    context: "Professional audience dealing with burnout.",
    status: POST_STATUSES[1],
    hook: "Clarity often solves what pressure never will.",
    body: "Slide outline: five signals that point to confusion, not laziness, and one next step for each.",
    cta: "Share this with someone carrying too much mental noise.",
    hashtags: ["#Leadership", "#Clarity", "#Change180"],
    visualDirection: "Clean carousel with teal numerals and cream backgrounds.",
    createdAt: "2026-03-11T15:00:00.000Z",
    scheduledFor: "2026-03-18",
  },
  {
    id: "demo-3",
    platform: "Facebook",
    contentType: "Reel Script",
    pillar: "Hope and Transformation",
    goal: "Community Building",
    tone: "Warm and invitational",
    topic: "Hope after self-sabotage",
    context: "Speak to people who feel behind in life.",
    status: POST_STATUSES[2],
    hook: "Your story is not over because you lost momentum.",
    body: "Short reel script about returning to truth after shame and restarting without dramatics.",
    cta: "Message Change180 if you are ready to rebuild with guidance.",
    hashtags: ["#Hope", "#Healing", "#Change180"],
    visualDirection: "Talking-head reel with subtitles and warm natural light.",
    createdAt: "2026-03-12T15:00:00.000Z",
    scheduledFor: "2026-03-20",
  },
];

export const demoPerformanceLogs = [
  {
    id: "log-1",
    postTitle: "Reset after a hard week",
    platform: "Instagram",
    outcome: "Strong saves and shares",
    insight: "Short hooks paired with grounded encouragement performed best.",
    nextMove: "Create two more mindset reset captions next week.",
    loggedAt: "2026-03-13T15:00:00.000Z",
  },
];
